[project]
name = "whack-a-penguin"
clarinet_version = "1.0.0"

[contracts.whack-a-penguin]
path = "contracts/whack-a-penguin.clar"

[networks]
[networks.testnet]
name = "testnet"
stacks_node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
stacks_node_p2p_address = "https://stacks-node-api.testnet.stacks.co"
stacks_node_event_source_address = "https://stacks-node-api.testnet.stacks.co"
stacks_node_burn_address = "ST000000000000000000002AMW42H"
chain_id = 2147483648
[networks.testnet.accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
balance = 1000000000000
[networks.testnet.accounts.wallet_1]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5"
balance = 1000000000000
[networks.testnet.accounts.wallet_2]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG"
balance = 1000000000000
[networks.testnet.accounts.wallet_3]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC"
balance = 1000000000000
[networks.testnet.accounts.wallet_4]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST2NEB84ASENDXKYGJPQW86YXQCEFEX2ZQPGP4Z4"
balance = 1000000000000
[networks.testnet.accounts.wallet_5]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST2REHHS5J3CERCRBEPMGH7921Q6PYKAADT7JP2VB"
balance = 1000000000000
[networks.testnet.accounts.wallet_6]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST3AM1A56AK2C1XAFJ4115ZSV26EB49BVQ10MGCS0"
balance = 1000000000000
[networks.testnet.accounts.wallet_7]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST3PF13W7Z0RRM42A8VJRVG8H1G0W4K3R5NB5X3C8"
balance = 1000000000000
[networks.testnet.accounts.wallet_8]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "ST3NBRSFKX28FQ0Z0T1XK5R0JJGC4J8N5N2B4S6K9"
balance = 1000000000000
[networks.testnet.accounts.wallet_9]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing balance cousin become tomorrow begin west a giraffe letter grace chopper voice boxer about"
address = "STNHKEPYEPJ8ET55ZZ0M5A34J0R3N5FM2CMMMAZ6"
balance = 1000000000000
